### ISSUE TITLE
Cookies issue? "ConnectionError: 403 Forbidden! "

### ISSUE THREAD

**Issue by jeJerry339** [ppldl/p_pl_dl#13]
Hello! First of all thank you for this codes, and I'm very new at this. However, I met an issue and it's likely due of my lack understanding of all of these. I did diligence by looking at closed issues for troubleshooting it myself, but I think my issue is the same as otongS. 

I'm using this cookies extension as suggested; https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/
The issue still persist. 

> C:\Users\USER\p_pl_dl-main>python p_pl_dl_main.py -i "C:\Users\USER\Playlist\urls.txt" -c "C:\Users\USER\Playlist\Cookies\spankbang.com_cookies.txt" -d "C:\Users\USER\Playlist\Videos"
> Working download directory: C:\Users\USER\Playlist\Videos
> Cookies source: C:\Users\USER\Playlist\Cookies\spankbang.com_cookies.txt
> Using the following input source: C:\Users\USER\Playlist\urls.txt
> Video limit per URL = None
> URL: https://spankbang.com/9txac/playlist/jav+sc
> 
> Detected websites:
> {
>     "lewdthots": false,
>     "pornhub": false,
>     "porntrex": false,
>     "pornve": false,
>     "spankbang": true,
>     "xhamster": false,
>     "xvideos": false,
>     "youporn": false
> }
> 
> Running spankbang extractor for https://spankbang.com/9txac/playlist/jav+sc
> 
> Initial connection status: 403
> 
> 
> 
> Traceback (most recent call last):
>   File "C:\Users\USER\p_pl_dl-main\p_pl_dl_main.py", line 94, in main
>     dExtractors[sSite].run(sUrl, sCookieSource=None, nVideoLimit=nVideoLimit)       # Cookies should already be parsed and available when going through main
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\USER\p_pl_dl-main\p_pl_dl_sb.py", line 34, in run
>     raise ConnectionError(f"403 Forbidden! Please check if cookies are required! Private videos/playlists cannot be accessed without cookies!")
> ConnectionError: 403 Forbidden! Please check if cookies are required! Private videos/playlists cannot be accessed without cookies!

Any help would be appreciated :) Cheers.

**Comment by SUMMERlove1** [comment]
> Hello! First of all thank you for this codes, and I'm very new at this. However, I met an issue and it's likely due of my lack understanding of all of these. I did diligence by looking at closed issues for troubleshooting it myself, but I think my issue is the same as otongS.
> 
> I'm using this cookies extension as suggested; https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/ The issue still persist.
> 
> > C:\Users\USER\p_pl_dl-main>python p_pl_dl_main.py -i "C:\Users\USER\Playlist\urls.txt" -c "C:\Users\USER\Playlist\Cookies\spankbang.com_cookies.txt" -d "C:\Users\USER\Playlist\Videos"
> > Working download directory: C:\Users\USER\Playlist\Videos
> > Cookies source: C:\Users\USER\Playlist\Cookies\spankbang.com_cookies.txt
> > Using the following input source: C:\Users\USER\Playlist\urls.txt
> > Video limit per URL = None
> > URL: https://spankbang.com/9txac/playlist/jav+sc
> > Detected websites:
> > {
> > "lewdthots": false,
> > "pornhub": false,
> > "porntrex": false,
> > "pornve": false,
> > "spankbang": true,
> > "xhamster": false,
> > "xvideos": false,
> > "youporn": false
> > }
> > Running spankbang extractor for https://spankbang.com/9txac/playlist/jav+sc
> > Initial connection status: 403
> > Traceback (most recent call last):
> > File "C:\Users\USER\p_pl_dl-main\p_pl_dl_main.py", line 94, in main
> > dExtractors[sSite].run(sUrl, sCookieSource=None, nVideoLimit=nVideoLimit)       # Cookies should already be parsed and available when going through main
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "C:\Users\USER\p_pl_dl-main\p_pl_dl_sb.py", line 34, in run
> > raise ConnectionError(f"403 Forbidden! Please check if cookies are required! Private videos/playlists cannot be accessed without cookies!")
> > ConnectionError: 403 Forbidden! Please check if cookies are required! Private videos/playlists cannot be accessed without cookies!
> 
> Any help would be appreciated :) Cheers.
