### ISSUE TITLE
Can't download from Spankbang

### ISSUE THREAD

**Issue by Katylar** [ppldl/p_pl_dl#4]
I keep getting this error when the script tries to run the spankbang extractor:

`
Traceback (most recent call last):
  File "p_pl_dl_main.py", line 91, in main
    dExtractors[sSite].run(sUrl, sCookieSource=None)        # Cookies should already be parsed and available when going through main
  File "F:\Desktop\Tools\p_pl_dl-main\p_pl_dl_sb.py", line 22, in run
    dl_common.addCipher("https://spankbang.com")
  File "F:\Desktop\Tools\p_pl_dl-main\p_pl_dl_common.py", line 102, in addCipher
    session.mount(sPrefix, CipherAdapter())
  File "C:\Code\Python\3.6.5\lib\site-packages\requests\adapters.py", line 130, in __init__
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
  File "F:\Desktop\Tools\p_pl_dl-main\p_pl_dl_common.py", line 147, in init_poolmanager
    context = create_urllib3_context(ciphers=CIPHERS)
  File "C:\Code\Python\3.6.5\lib\site-packages\urllib3\util\ssl_.py", line 292, in create_urllib3_context
    context.set_ciphers(ciphers or DEFAULT_CIPHERS)
ssl.SSLError: ('No cipher can be selected.',)
`

**Comment by ppldl** [comment]
Pull and try again. The cipher thing might not be needed anymore.

**Comment by ppldl** [comment]
Closing due to no further activity.
